let quotes = ["i love cheese",
    "lebron?",
    "Forsaken V2",
    "marko and anas worked hard for yall",
    "thanks anas for tickles.store",
    "did you know 1+1=2?",
    "stop begging for games please let me sleep",
    "try clicking on me",
    "im not making money of off this :(",
    "chicken jockey",
    "took inspiration from brunys ixl for this remake",
    "ty for playing",
    "whats ur favorite game?",
    "try out the game quake",
    "panic key exists (press `) but doesnt work in games",
    "gay",
    "thanks anas",
    "cheddar",
    "WE ARE FORSAKEN",
    "pay me to add smth here cuz why not?",
]